# MySQL Database Service
apiVersion: v1
kind: Service
metadata:
  name: mysqldb  # Este nombre debe coincidir con el que usa la app
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysqldb  # Cambié a mysqldb
  clusterIP: None
---
# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb  # Cambié a mysqldb
spec:
  selector:
    matchLabels:
      app: mysqldb  # Cambié a mysqldb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqldb  # Cambié a mysqldb
    spec:
      imagePullSecrets:
      - name: regcred  # Para imágenes privadas
      containers:
      - image: mysql:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mario14y15."
        - name: MYSQL_DATABASE
          value: "cremeria"
        - name: MYSQL_PASSWORD
          value: "mario14y15."
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        emptyDir: {}
---
# Spring Boot Application Service
apiVersion: v1
kind: Service
metadata:
  name: desarrolloweb-service  # Nombre más descriptivo
spec:
  type: LoadBalancer
  ports:
  - port: 3600  # Mismo puerto que docker-compose
    targetPort: 3600
    protocol: TCP
  selector:
    app: desarrolloweb  # Cambié a desarrolloweb
---
# Spring Boot Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: desarrolloweb  # Cambié a desarrolloweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desarrolloweb  # Cambié a desarrolloweb
  template:
    metadata:
      labels:
        app: desarrolloweb  # Cambié a desarrolloweb
    spec:
      containers:
      - name: backcontainer  # Mismo nombre que en docker-compose
        image: mariohqe/cremeria-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3600
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        - name: DATABASE_URL
          value: "jdbc:mysql://mysqldb:3306/cremeria?createDatabaseIfNotExist=true"
        - name: DATABASE_USERNAME
          value: "root"
        - name: DATABASE_PASSWORD
          value: "mario14y15."
        - name: stripe.secretkey
          value: "sk_test_51RRpwwRS5ApzbFdePxJPtFPIU5SoWXi6a9r3BfW92TNd6cPSTMf3n3BfnazI9t0KBir2VbNPYLifXVjSVUmPrlPX001PqO7jS7"
        - name: stripe.webhook.secret
          value: "whsec_0413b21f46b91831209ef4ada5ff08fd7428b314238748ae2a4819d5dad629a4"
        - name: aws.s3.acceskey
          value: "AKIAWYOPDF3QT7NDAJUC"
        - name: aws.s3.secretkey
          value: "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"
        - name: spring.mail.username
          value: "marioelpro08@gmail.com"
        - name: spring.mail.password
          value: "bmch rbeg tfmx ondv"