steps:
  # Mostrar variables de entorno (debug)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "PROJECT_ID: $PROJECT_ID"
        echo "COMMIT_SHA: $COMMIT_SHA"
        echo "BRANCH_NAME: $BRANCH_NAME"
        echo "BUILD_ID: $BUILD_ID"
  
  # Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/desarrolloweb:$COMMIT_SHA', '.']
  
  # Subir la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/desarrolloweb:$COMMIT_SHA']
  
  # Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mnimarket'
      - '--image'
      - 'gcr.io/$PROJECT_ID/desarrolloweb:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'PORT=8080'

# Opciones de construcción
options:
  logging: CLOUD_LOGGING_ONLY

# Imágenes que se crearán
images:
  - 'gcr.io/$PROJECT_ID/desarrolloweb:$COMMIT_SHA' 