version: "3.8"

services:
  desarrolloweb:
    container_name: backcontainer
    build: ./desarrolloweb
    ports:
      - "3600:3600"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:mysql://minimarket.ckbesa4wqwo4.us-east-1.rds.amazonaws.com:3306/minimarket?createDatabaseIfNotExist=true
      - DATABASE_USERNAME=adminsq
      - DATABASE_PASSWORD=Mario14y15.
      - STRIPE_SECRET_KEY=sk_test_51RRpwwRS5ApzbFdePxJPtFPIU5SoWXi6a9r3BfW92TNd6cPSTMf3n3BfnazI9t0KBir2VbNPYLifXVjSVUmPrlPX001PqO7jS7
      - STRIPE_WEBHOOK_SECRET=whsec_9850a314cfa962c23f3616368e571af42d3d78f675cac0825c67d2d5bdffbee5
      - AWS_ACCESS_KEY=AKIAWYOPDF3QT7NDAJUC
      - AWS_SECRET_KEY=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
      - MAIL_USERNAME=marioelpro08@gmail.com
      - MAIL_PASSWORD=bmch rbeg tfmx ondv
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_KEY_STORE=classpath:desarrolloweb-ssl.p12
      - SERVER_SSL_KEY_STORE_PASSWORD=password123
      - SERVER_SSL_KEY_STORE_TYPE=PKCS12
      - SERVER_SSL_KEY_ALIAS=desarrolloweb-ssl
      - SERVER_PORT=8443
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - ./nginx/conf.d:/etc/nginx/conf
        - ./nginx/ssl:/etc/nginx/ssl
        - ./certs:/etc/nginx/certs
    depends_on:
        - desarrolloweb
    networks:
        - backend

networks:
  backend:
    driver: bridge

