version: "3.8"

services:
  desarrolloweb:
    container_name: backcontainer
    build: ./desarrolloweb
    ports:
      - "3600:3600"
    environment:
      - DATABASE_URL= jdbc:mysql://minimarket.ckbesa4wqwo4.us-east-1.rds.amazonaws.com:3306/minimarket?createDatabaseIfNotExist=true
      - DATABASE_USERNAME=adminsq
      - DATABASE_PASSWORD=Mario14y15.
      - SPRING_PROFILES_ACTIVE=docker


