version: "3.8"

services:
  desarrolloweb:
    container_name: backcontainer
    build: ./desarrolloweb
    ports:
      - "3600:3600"
    environment:
      - DATABASE_URL= jdbc:mysql://mysqldb:3306/cremeria?createDatabaseIfNotExist=true
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=mario14y15.
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysqldb
 

  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - "3307:3306" # cambia a 3307 si el 3306 local está ocupado
    environment:
      MYSQL_DATABASE: cremeria
      MYSQL_PASSWORD: mario14y15.
      MYSQL_ROOT_PASSWORD: mario14y15.
   
    

